version: '3.8'

services:
  cropguard-web:
    build: .
    container_name: cropguard_web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DB_PATH=data/cropguard.db
    devices:
      - "/dev/video0:/dev/video0" # Passthrough for webcam
    restart: unless-stopped
